# Generated by Django 4.0.6 on 2022-10-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_invoice_file_invoice_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchase_expense',
            fields=[
                ('expenseid', models.AutoField(primary_key=True, serialize=False, verbose_name='eid')),
                ('expense_no', models.IntegerField(default=1000)),
                ('date', models.DateField()),
                ('expenseaccount', models.CharField(max_length=100, null=True)),
                ('expensetype', models.CharField(max_length=100, null=True)),
                ('hsn_sac', models.CharField(max_length=100, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('paidthrough', models.CharField(max_length=100, null=True)),
                ('vendor', models.CharField(max_length=100, null=True)),
                ('gsttype', models.CharField(max_length=100, null=True)),
                ('sourceofsupply', models.CharField(max_length=100, null=True)),
                ('destinofsupply', models.CharField(max_length=100, null=True)),
                ('customer', models.CharField(max_length=100, null=True)),
                ('tax', models.CharField(max_length=100, null=True)),
                ('reference', models.CharField(max_length=100, null=True)),
                ('note', models.CharField(max_length=255, null=True)),
                ('file', models.FileField(null=True, upload_to='purchase/expense')),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='title',
            new_name='c',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='taxamount',
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='file',
            field=models.FileField(null=True, upload_to='purchase/bill'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='file',
            field=models.FileField(null=True, upload_to='purchase/purchaseorder'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='companyname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='mobile',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='pincode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='street',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='title',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
