# Generated by Django 4.0.6 on 2022-10-05 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_purchase_expense_rename_title_customer_c_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='c',
            new_name='title',
        ),
    ]
