# Generated by Django 4.0.6 on 2022-10-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_customer_date_alter_cust_statment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='receivables',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
