# Generated by Django 4.0.6 on 2022-10-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_customer_receivables'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='file',
            field=models.FileField(default=1, upload_to='Customer'),
            preserve_default=False,
        ),
    ]
