# Generated by Django 4.0.6 on 2022-10-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0043_alter_customer_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='receivables',
            field=models.FloatField(null=True),
        ),
    ]
